
{
  parserClass="com.simpleplugin.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiImplClassSuffix="Impl"
  psiPackage="com.simpleplugin.psi"
  psiImplPackage="com.simpleplugin.psi.impl"

  elementTypeHolderClass="com.simpleplugin.psi.SimpleTypes"
  elementTypeClass="com.simpleplugin.psi.SimpleElementType"
  tokenTypeClass="com.simpleplugin.psi.SimpleTokenType"
}

Grammar ::=simpleRules*

private simpleRules ::= Rule SEPARATOR textPattern featurePattern|COMMENT|CRLF

private textPattern ::= wordstem textPattern*

private wordstem ::= (SINGLEQUOTATION stem SINGLEQUOTATION)|(DOUBLEQUOTATION word DOUBLEQUOTATION)

private featurePattern ::= primaryPattern featurePattern*

private primaryPattern ::= simplePattern (OR primaryPattern)*

private simplePattern ::= teminal (PLUS simplePattern)*

teminal ::= [NOT] FEATURE|LCURLY featurePattern RCURLY

stem ::= [NOT] onestem (OR [NOT] onestem)*

word ::= [NOT] oneword (OR [NOT] oneword)*
